### ISSUE TITLE
Unable to use onionsearch

### ISSUE THREAD

**Issue by elpagano3** [tracelabs/tlosint-live#150]
If i try to use onionsearch on terminal i get this error:

└─$ onionsearch   
Traceback (most recent call last):
  File "/usr/local/bin/onionsearch", line 33, in <module>
    sys.exit(load_entry_point('onionsearch==1.3', 'console_scripts', 'onionsearch')())
  File "/usr/local/bin/onionsearch", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 957, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for onionsearch

**Comment by cyb3rw0lf** [comment]
Same as for buster, please try reinstalling
```
cd /usr/share/OnionSearch
sudo python3 setup.py install
```
