### ISSUE TITLE
Unable to use buster on terminal

### ISSUE THREAD

**Issue by elpagano3** [tracelabs/tlosint-live#151]
If i try to use buster on terminal:

└─$ buster   
Traceback (most recent call last):
  File "/usr/local/bin/buster", line 33, in <module>
    sys.exit(load_entry_point('buster==1.0.0', 'console_scripts', 'buster')())
  File "/usr/local/bin/buster", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 957, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for buster

**Comment by cyb3rw0lf** [comment]
This should fix it, please try:

```
cd /usr/share/buster
sudo python3 setup.py install
```
